# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a073072acf0bf614979e3225e07ceefa1096e490c9ad8567a0ea54f3cab32304441e09f362f62db2d586c2917ebcc3c60e4cb26a89543d813d2c2c9c5c3c3f1d

test:
  secret_key_base: 4889863072a019f1ce872986d256bba58228017a6e6591532a3d49486c4785a4012fc4ad8a0993d8b485603745f5cef5e5085da42a8ef8b311b8a4c030517d84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
